In [36]:
import pandas as pd

In [37]:
# data presetting

df = pd.read_csv("anime.csv")
pd.set_option("display.max_colwidth",None)
df.to_string(index=False)

df

,Rank,Title,Score
0,1,"Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr 2009 - Jul 20103,218,472 membersManga StoreVolume 1€4.58Preview",9.10
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473,707 members",9.07
2,3,"Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 - Dec 2022474,138 members",9.06
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 members",9.06
4,5,"Shingeki no Kyojin Season 3 Part 2TV (10 eps)Apr 2019 - Jul 20192,146,679 membersManga StoreVolume 1€10.99Preview",9.05
5,6,"Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 members",9.04
6,7,"Gintama: The FinalMovie (1 eps)Jan 2021 - Jan 2021137,208 members",9.04
7,8,"Hunter x Hunter TV (148 eps)Oct 2011 - Sep 20142,701,154 members",9.04
8,9,"Kaguya-sama wa Kokurasetai: Ultra RomanticTV (13 eps)Apr 2022 - Jun 2022851,445 members",9.04
9,10,"Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2013313,446 members",9.03
10,11,"Shingeki no Kyojin: The Final Season - Kanketsu-henSpecial (2 eps)Mar 2023 - May 2023472,340 membersManga StoreVolume 1€10.99Preview",9.03
11,12,"Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Mar 1997309,193 members",9.02
12,13,"Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (13 eps)Jul 2023 - Aug 2023 178,482 members",8.99
13,14,"Fruits Basket: The FinalTV (13 eps)Apr 2021 - Jun 2021443,882 membersManga StoreVolume 1€6.66Preview",8.99
14,15,"Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 members",8.98
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,418 members",8.94
16,17,"Koe no KatachiMovie (1 eps)Sep 2016 - Sep 20162,228,957 membersManga StoreVolume 1€10.99Preview",8.94
17,18,"3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 - Mar 2018388,358 members",8.93
18,19,"Clannad: After StoryTV (24 eps)Oct 2008 - Mar 20091,160,879 members",8.93
19,20,"Code Geass: Hangyaku no Lelouch R2TV (25 eps)Apr 2008 - Sep 20081,720,715 members",8.91
20,21,"Gintama Movie 2: Kanketsu-hen - Yorozuya yo Eien NareMovie (1 eps)Jul 2013 - Jul 2013232,388 members",8.91
21,22,"Violet Evergarden MovieMovie (1 eps)Sep 2020 - Sep 2020564,225 members",8.89
22,23,"Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 - Aug 2017385,248 members",8.88
23,24,"Gintama.: Shirogane no Tamashii-hen - Kouhan-senTV (14 eps)Jul 2018 - Oct 2018189,172 members",8.88
24,25,"MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081 members",8.87
25,26,"Kimi no Na wa.Movie (1 eps)Aug 2016 - Aug 20162,635,814 membersManga StoreVolume 1€4.58Preview",8.84
26,27,"Kaguya-sama wa Kokurasetai: First Kiss wa OwaranaiMovie (1 eps)Dec 2022 - Dec 2022205,150 members",8.84
27,28,"Bocchi the Rock!TV (12 eps)Oct 2022 - Dec 2022464,981 members",8.83
28,29,"The First Slam DunkMovie (1 eps)Dec 2022 - Dec 202227,063 members",8.83
29,30,"Vinland Saga Season 2TV (24 eps)Jan 2023 - Jun 2023495,454 membersManga StoreVolume 1€17.99Preview",8.82
30,31,"Jujutsu Kaisen 2nd SeasonTV (23 eps)Jul 2023 - Aug 2023 556,301 members",8.82
31,32,"Gintama.: Shirogane no Tamashii-henTV (12 eps)Jan 2018 - Mar 2018203,540 members",8.81
32,33,"Kingdom 3rd SeasonTV (26 eps)Apr 2020 - Oct 202193,645 members",8.81
33,34,"Mob Psycho 100 IITV (13 eps)Jan 2019 - Apr 20191,458,089 members",8.80
34,35,"Shingeki no Kyojin: The Final SeasonTV (16 eps)Dec 2020 - Mar 20211,882,760 membersManga StoreVolume 1€10.99Preview",8.80
35,36,"Kimetsu no Yaiba: Yuukaku-henTV (11 eps)Dec 2021 - Feb 20221,302,152 members",8.79
36,37,"Kizumonogatari III: Reiketsu-henMovie (1 eps)Jan 2017 - Jan 2017445,640 membersManga StorePart1€9.99Preview",8.79
37,38,"""Oshi no Ko""TV (11 eps)Apr 2023 - Jun 2023645,856 members",8.79
38,39,"Haikyuu!! Karasuno Koukou vs. Shiratorizawa Gakuen KoukouTV (10 eps)Oct 2016 - Dec 20161,157,497 members",8.78
39,40,"Sen to Chihiro no KamikakushiMovie (1 eps)Jul 2001 - Jul 20011,784,960 members",8.78
40,41,"Monogatari Series: Second SeasonTV (26 eps)Jul 2013 - Dec 2013653,257 membersManga StoreVolume 1€9.99Preview",8.77
41,42,"Shingeki no Kyojin: The Final Season Part 2TV (12 eps)Jan 2022 - Apr 20221,170,165 membersManga StoreVolume 1€10.99Preview",8.77
42,43,"Hajime no IppoTV (75 eps)Oct 2000 - Mar 2002558,435 members",8.76
43,44,"Cowboy BebopTV (26 eps)Apr 1998 - Apr 19991,796,109 members",8.75
44,45,"Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 202255,833 members",8.75
45,46,"Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,403,669 membersManga StoreVolume 1€17.99Preview",8.74
46,47,"Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 2014 - Dec 2014257,622 membersManga StoreVolume 1€10.99Preview",8.73
47,48,"Shouwa Genroku Rakugo Shinjuu: Sukeroku Futatabi-henTV (12 eps)Jan 2017 - Mar 2017182,450 membersManga StoreVolume 1€12.99Preview",8.72
48,49,"Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 2022600,098 members",8.71
49,50,"Rurouni Kenshin: Meiji Kenkaku Romantan - Tsuioku-henOVA (4 eps)Feb 1999 - Sep 1999271,108 members",8.71

In [38]:
# make a new column for the name of the animes

In [39]:
# Adding anime name
def Real_name(x):
    box = ""
    flg = True
    for i in x:
        if i == "(":
            break
        if flg == True:
            box += i 
    return box

df["Anime_name"] = df["Title"].apply(Real_name)

df

,Rank,Title,Score,Anime_name
0,1,"Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr 2009 - Jul 20103,218,472 membersManga StoreVolume 1€4.58Preview",9.10,Fullmetal Alchemist: BrotherhoodTV
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473,707 members",9.07,Steins;GateTV
2,3,"Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 - Dec 2022474,138 members",9.06,Bleach: Sennen Kessen-henTV
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 members",9.06,Gintama°TV
4,5,"Shingeki no Kyojin Season 3 Part 2TV (10 eps)Apr 2019 - Jul 20192,146,679 membersManga StoreVolume 1€10.99Preview",9.05,Shingeki no Kyojin Season 3 Part 2TV
5,6,"Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 members",9.04,Gintama'TV
6,7,"Gintama: The FinalMovie (1 eps)Jan 2021 - Jan 2021137,208 members",9.04,Gintama: The FinalMovie
7,8,"Hunter x Hunter TV (148 eps)Oct 2011 - Sep 20142,701,154 members",9.04,Hunter x Hunter TV
8,9,"Kaguya-sama wa Kokurasetai: Ultra RomanticTV (13 eps)Apr 2022 - Jun 2022851,445 members",9.04,Kaguya-sama wa Kokurasetai: Ultra RomanticTV
9,10,"Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2013313,446 members",9.03,Gintama': EnchousenTV
10,11,"Shingeki no Kyojin: The Final Season - Kanketsu-henSpecial (2 eps)Mar 2023 - May 2023472,340 membersManga StoreVolume 1€10.99Preview",9.03,Shingeki no Kyojin: The Final Season - Kanketsu-henSpecial
11,12,"Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Mar 1997309,193 members",9.02,Ginga Eiyuu DensetsuOVA
12,13,"Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (13 eps)Jul 2023 - Aug 2023 178,482 members",8.99,Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV
13,14,"Fruits Basket: The FinalTV (13 eps)Apr 2021 - Jun 2021443,882 membersManga StoreVolume 1€6.66Preview",8.99,Fruits Basket: The FinalTV
14,15,"Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 members",8.98,Gintama.TV
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,418 members",8.94,GintamaTV
16,17,"Koe no KatachiMovie (1 eps)Sep 2016 - Sep 20162,228,957 membersManga StoreVolume 1€10.99Preview",8.94,Koe no KatachiMovie
17,18,"3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 - Mar 2018388,358 members",8.93,3-gatsu no Lion 2nd SeasonTV
18,19,"Clannad: After StoryTV (24 eps)Oct 2008 - Mar 20091,160,879 members",8.93,Clannad: After StoryTV
19,20,"Code Geass: Hangyaku no Lelouch R2TV (25 eps)Apr 2008 - Sep 20081,720,715 members",8.91,Code Geass: Hangyaku no Lelouch R2TV
20,21,"Gintama Movie 2: Kanketsu-hen - Yorozuya yo Eien NareMovie (1 eps)Jul 2013 - Jul 2013232,388 members",8.91,Gintama Movie 2: Kanketsu-hen - Yorozuya yo Eien NareMovie
21,22,"Violet Evergarden MovieMovie (1 eps)Sep 2020 - Sep 2020564,225 members",8.89,Violet Evergarden MovieMovie
22,23,"Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 - Aug 2017385,248 members",8.88,Owarimonogatari 2nd SeasonTV
23,24,"Gintama.: Shirogane no Tamashii-hen - Kouhan-senTV (14 eps)Jul 2018 - Oct 2018189,172 members",8.88,Gintama.: Shirogane no Tamashii-hen - Kouhan-senTV
24,25,"MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081 members",8.87,MonsterTV
25,26,"Kimi no Na wa.Movie (1 eps)Aug 2016 - Aug 20162,635,814 membersManga StoreVolume 1€4.58Preview",8.84,Kimi no Na wa.Movie
26,27,"Kaguya-sama wa Kokurasetai: First Kiss wa OwaranaiMovie (1 eps)Dec 2022 - Dec 2022205,150 members",8.84,Kaguya-sama wa Kokurasetai: First Kiss wa OwaranaiMovie
27,28,"Bocchi the Rock!TV (12 eps)Oct 2022 - Dec 2022464,981 members",8.83,Bocchi the Rock!TV
28,29,"The First Slam DunkMovie (1 eps)Dec 2022 - Dec 202227,063 members",8.83,The First Slam DunkMovie
29,30,"Vinland Saga Season 2TV (24 eps)Jan 2023 - Jun 2023495,454 membersManga StoreVolume 1€17.99Preview",8.82,Vinland Saga Season 2TV
30,31,"Jujutsu Kaisen 2nd SeasonTV (23 eps)Jul 2023 - Aug 2023 556,301 members",8.82,Jujutsu Kaisen 2nd SeasonTV
31,32,"Gintama.: Shirogane no Tamashii-henTV (12 eps)Jan 2018 - Mar 2018203,540 members",8.81,Gintama.: Shirogane no Tamashii-henTV
32,33,"Kingdom 3rd SeasonTV (26 eps)Apr 2020 - Oct 202193,645 members",8.81,Kingdom 3rd SeasonTV
33,34,"Mob Psycho 100 IITV (13 eps)Jan 2019 - Apr 20191,458,089 members",8.80,Mob Psycho 100 IITV
34,35,"Shingeki no Kyojin: The Final SeasonTV (16 eps)Dec 2020 - Mar 20211,882,760 membersManga StoreVolume 1€10.99Preview",8.80,Shingeki no Kyojin: The Final SeasonTV
35,36,"Kimetsu no Yaiba: Yuukaku-henTV (11 eps)Dec 2021 - Feb 20221,302,152 members",8.79,Kimetsu no Yaiba: Yuukaku-henTV
36,37,"Kizumonogatari III: Reiketsu-henMovie (1 eps)Jan 2017 - Jan 2017445,640 membersManga StorePart1€9.99Preview",8.79,Kizumonogatari III: Reiketsu-henMovie
37,38,"""Oshi no Ko""TV (11 eps)Apr 2023 - Jun 2023645,856 members",8.79,"""Oshi no Ko""TV"
38,39,"Haikyuu!! Karasuno Koukou vs. Shiratorizawa Gakuen KoukouTV (10 eps)Oct 2016 - Dec 20161,157,497 members",8.78,Haikyuu!! Karasuno Koukou vs. Shiratorizawa Gakuen KoukouTV
39,40,"Sen to Chihiro no KamikakushiMovie (1 eps)Jul 2001 - Jul 20011,784,960 members",8.78,Sen to Chihiro no KamikakushiMovie
40,41,"Monogatari Series: Second SeasonTV (26 eps)Jul 2013 - Dec 2013653,257 membersManga StoreVolume 1€9.99Preview",8.77,Monogatari Series: Second SeasonTV
41,42,"Shingeki no Kyojin: The Final Season Part 2TV (12 eps)Jan 2022 - Apr 20221,170,165 membersManga StoreVolume 1€10.99Preview",8.77,Shingeki no Kyojin: The Final Season Part 2TV
42,43,"Hajime no IppoTV (75 eps)Oct 2000 - Mar 2002558,435 members",8.76,Hajime no IppoTV
43,44,"Cowboy BebopTV (26 eps)Apr 1998 - Apr 19991,796,109 members",8.75,Cowboy BebopTV
44,45,"Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 202255,833 members",8.75,Kingdom 4th SeasonTV
45,46,"Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,403,669 membersManga StoreVolume 1€17.99Preview",8.74,Vinland SagaTV
46,47,"Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 2014 - Dec 2014257,622 membersManga StoreVolume 1€10.99Preview",8.73,Mushishi Zoku Shou 2nd SeasonTV
47,48,"Shouwa Genroku Rakugo Shinjuu: Sukeroku Futatabi-henTV (12 eps)Jan 2017 - Mar 2017182,450 membersManga StoreVolume 1€12.99Preview",8.72,Shouwa Genroku Rakugo Shinjuu: Sukeroku Futatabi-henTV
48,49,"Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 2022600,098 members",8.71,Mob Psycho 100 IIITV
49,50,"Rurouni Kenshin: Meiji Kenkaku Romantan - Tsuioku-henOVA (4 eps)Feb 1999 - Sep 1999271,108 members",8.71,Rurouni Kenshin: Meiji Kenkaku Romantan - Tsuioku-henOVA

In [40]:
#make a new column for episode count

In [41]:
# Adding episodes number

def Fetch(x):
    data = ""
    check = False
    for i in x:
        if i == "(":
            check = True
            continue
            
        if i ==")":
            check = False
            break

        if check==True:
            data+=i
    return data

df["Episodes"] = df["Title"].apply(Fetch).str.removesuffix("eps").astype(int)

df

,Rank,Title,Score,Anime_name,Episodes
0,1,"Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr 2009 - Jul 20103,218,472 membersManga StoreVolume 1€4.58Preview",9.10,Fullmetal Alchemist: BrotherhoodTV,64
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473,707 members",9.07,Steins;GateTV,24
2,3,"Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 - Dec 2022474,138 members",9.06,Bleach: Sennen Kessen-henTV,13
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 members",9.06,Gintama°TV,51
4,5,"Shingeki no Kyojin Season 3 Part 2TV (10 eps)Apr 2019 - Jul 20192,146,679 membersManga StoreVolume 1€10.99Preview",9.05,Shingeki no Kyojin Season 3 Part 2TV,10
5,6,"Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 members",9.04,Gintama'TV,51
6,7,"Gintama: The FinalMovie (1 eps)Jan 2021 - Jan 2021137,208 members",9.04,Gintama: The FinalMovie,1
7,8,"Hunter x Hunter TV (148 eps)Oct 2011 - Sep 20142,701,154 members",9.04,Hunter x Hunter TV,148
8,9,"Kaguya-sama wa Kokurasetai: Ultra RomanticTV (13 eps)Apr 2022 - Jun 2022851,445 members",9.04,Kaguya-sama wa Kokurasetai: Ultra RomanticTV,13
9,10,"Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2013313,446 members",9.03,Gintama': EnchousenTV,13
10,11,"Shingeki no Kyojin: The Final Season - Kanketsu-henSpecial (2 eps)Mar 2023 - May 2023472,340 membersManga StoreVolume 1€10.99Preview",9.03,Shingeki no Kyojin: The Final Season - Kanketsu-henSpecial,2
11,12,"Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Mar 1997309,193 members",9.02,Ginga Eiyuu DensetsuOVA,110
12,13,"Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (13 eps)Jul 2023 - Aug 2023 178,482 members",8.99,Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV,13
13,14,"Fruits Basket: The FinalTV (13 eps)Apr 2021 - Jun 2021443,882 membersManga StoreVolume 1€6.66Preview",8.99,Fruits Basket: The FinalTV,13
14,15,"Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 members",8.98,Gintama.TV,12
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,418 members",8.94,GintamaTV,201
16,17,"Koe no KatachiMovie (1 eps)Sep 2016 - Sep 20162,228,957 membersManga StoreVolume 1€10.99Preview",8.94,Koe no KatachiMovie,1
17,18,"3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 - Mar 2018388,358 members",8.93,3-gatsu no Lion 2nd SeasonTV,22
18,19,"Clannad: After StoryTV (24 eps)Oct 2008 - Mar 20091,160,879 members",8.93,Clannad: After StoryTV,24
19,20,"Code Geass: Hangyaku no Lelouch R2TV (25 eps)Apr 2008 - Sep 20081,720,715 members",8.91,Code Geass: Hangyaku no Lelouch R2TV,25
20,21,"Gintama Movie 2: Kanketsu-hen - Yorozuya yo Eien NareMovie (1 eps)Jul 2013 - Jul 2013232,388 members",8.91,Gintama Movie 2: Kanketsu-hen - Yorozuya yo Eien NareMovie,1
21,22,"Violet Evergarden MovieMovie (1 eps)Sep 2020 - Sep 2020564,225 members",8.89,Violet Evergarden MovieMovie,1
22,23,"Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 - Aug 2017385,248 members",8.88,Owarimonogatari 2nd SeasonTV,7
23,24,"Gintama.: Shirogane no Tamashii-hen - Kouhan-senTV (14 eps)Jul 2018 - Oct 2018189,172 members",8.88,Gintama.: Shirogane no Tamashii-hen - Kouhan-senTV,14
24,25,"MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081 members",8.87,MonsterTV,74
25,26,"Kimi no Na wa.Movie (1 eps)Aug 2016 - Aug 20162,635,814 membersManga StoreVolume 1€4.58Preview",8.84,Kimi no Na wa.Movie,1
26,27,"Kaguya-sama wa Kokurasetai: First Kiss wa OwaranaiMovie (1 eps)Dec 2022 - Dec 2022205,150 members",8.84,Kaguya-sama wa Kokurasetai: First Kiss wa OwaranaiMovie,1
27,28,"Bocchi the Rock!TV (12 eps)Oct 2022 - Dec 2022464,981 members",8.83,Bocchi the Rock!TV,12
28,29,"The First Slam DunkMovie (1 eps)Dec 2022 - Dec 202227,063 members",8.83,The First Slam DunkMovie,1
29,30,"Vinland Saga Season 2TV (24 eps)Jan 2023 - Jun 2023495,454 membersManga StoreVolume 1€17.99Preview",8.82,Vinland Saga Season 2TV,24
30,31,"Jujutsu Kaisen 2nd SeasonTV (23 eps)Jul 2023 - Aug 2023 556,301 members",8.82,Jujutsu Kaisen 2nd SeasonTV,23
31,32,"Gintama.: Shirogane no Tamashii-henTV (12 eps)Jan 2018 - Mar 2018203,540 members",8.81,Gintama.: Shirogane no Tamashii-henTV,12
32,33,"Kingdom 3rd SeasonTV (26 eps)Apr 2020 - Oct 202193,645 members",8.81,Kingdom 3rd SeasonTV,26
33,34,"Mob Psycho 100 IITV (13 eps)Jan 2019 - Apr 20191,458,089 members",8.80,Mob Psycho 100 IITV,13
34,35,"Shingeki no Kyojin: The Final SeasonTV (16 eps)Dec 2020 - Mar 20211,882,760 membersManga StoreVolume 1€10.99Preview",8.80,Shingeki no Kyojin: The Final SeasonTV,16
35,36,"Kimetsu no Yaiba: Yuukaku-henTV (11 eps)Dec 2021 - Feb 20221,302,152 members",8.79,Kimetsu no Yaiba: Yuukaku-henTV,11
36,37,"Kizumonogatari III: Reiketsu-henMovie (1 eps)Jan 2017 - Jan 2017445,640 membersManga StorePart1€9.99Preview",8.79,Kizumonogatari III: Reiketsu-henMovie,1
37,38,"""Oshi no Ko""TV (11 eps)Apr 2023 - Jun 2023645,856 members",8.79,"""Oshi no Ko""TV",11
38,39,"Haikyuu!! Karasuno Koukou vs. Shiratorizawa Gakuen KoukouTV (10 eps)Oct 2016 - Dec 20161,157,497 members",8.78,Haikyuu!! Karasuno Koukou vs. Shiratorizawa Gakuen KoukouTV,10
39,40,"Sen to Chihiro no KamikakushiMovie (1 eps)Jul 2001 - Jul 20011,784,960 members",8.78,Sen to Chihiro no KamikakushiMovie,1
40,41,"Monogatari Series: Second SeasonTV (26 eps)Jul 2013 - Dec 2013653,257 membersManga StoreVolume 1€9.99Preview",8.77,Monogatari Series: Second SeasonTV,26
41,42,"Shingeki no Kyojin: The Final Season Part 2TV (12 eps)Jan 2022 - Apr 20221,170,165 membersManga StoreVolume 1€10.99Preview",8.77,Shingeki no Kyojin: The Final Season Part 2TV,12
42,43,"Hajime no IppoTV (75 eps)Oct 2000 - Mar 2002558,435 members",8.76,Hajime no IppoTV,75
43,44,"Cowboy BebopTV (26 eps)Apr 1998 - Apr 19991,796,109 members",8.75,Cowboy BebopTV,26
44,45,"Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 202255,833 members",8.75,Kingdom 4th SeasonTV,26
45,46,"Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,403,669 membersManga StoreVolume 1€17.99Preview",8.74,Vinland SagaTV,24
46,47,"Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 2014 - Dec 2014257,622 membersManga StoreVolume 1€10.99Preview",8.73,Mushishi Zoku Shou 2nd SeasonTV,10
47,48,"Shouwa Genroku Rakugo Shinjuu: Sukeroku Futatabi-henTV (12 eps)Jan 2017 - Mar 2017182,450 membersManga StoreVolume 1€12.99Preview",8.72,Shouwa Genroku Rakugo Shinjuu: Sukeroku Futatabi-henTV,12
48,49,"Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 2022600,098 members",8.71,Mob Psycho 100 IIITV,12
49,50,"Rurouni Kenshin: Meiji Kenkaku Romantan - Tsuioku-henOVA (4 eps)Feb 1999 - Sep 1999271,108 members",8.71,Rurouni Kenshin: Meiji Kenkaku Romantan - Tsuioku-henOVA,4

In [42]:
#make a new column for time stamp

In [43]:
# Adding the date number

def Real_date(f):
    c= ""
    flg1 = False
    for i in f :
        if i ==")":
            flg1 = True
            continue

        if len(c) == 19:
            flg1 = False
            break

        if flg1 == True:
            c+= i
    return c

df["Anime_date"] = df["Title"].apply(Real_date)

df

,Rank,Title,Score,Anime_name,Episodes,Anime_date
0,1,"Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr 2009 - Jul 20103,218,472 membersManga StoreVolume 1€4.58Preview",9.10,Fullmetal Alchemist: BrotherhoodTV,64,Apr 2009 - Jul 2010
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473,707 members",9.07,Steins;GateTV,24,Apr 2011 - Sep 2011
2,3,"Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 - Dec 2022474,138 members",9.06,Bleach: Sennen Kessen-henTV,13,Oct 2022 - Dec 2022
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 members",9.06,Gintama°TV,51,Apr 2015 - Mar 2016
4,5,"Shingeki no Kyojin Season 3 Part 2TV (10 eps)Apr 2019 - Jul 20192,146,679 membersManga StoreVolume 1€10.99Preview",9.05,Shingeki no Kyojin Season 3 Part 2TV,10,Apr 2019 - Jul 2019
5,6,"Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 members",9.04,Gintama'TV,51,Apr 2011 - Mar 2012
6,7,"Gintama: The FinalMovie (1 eps)Jan 2021 - Jan 2021137,208 members",9.04,Gintama: The FinalMovie,1,Jan 2021 - Jan 2021
7,8,"Hunter x Hunter TV (148 eps)Oct 2011 - Sep 20142,701,154 members",9.04,Hunter x Hunter TV,148,Oct 2011 - Sep 2014
8,9,"Kaguya-sama wa Kokurasetai: Ultra RomanticTV (13 eps)Apr 2022 - Jun 2022851,445 members",9.04,Kaguya-sama wa Kokurasetai: Ultra RomanticTV,13,Apr 2022 - Jun 2022
9,10,"Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2013313,446 members",9.03,Gintama': EnchousenTV,13,Oct 2012 - Mar 2013
10,11,"Shingeki no Kyojin: The Final Season - Kanketsu-henSpecial (2 eps)Mar 2023 - May 2023472,340 membersManga StoreVolume 1€10.99Preview",9.03,Shingeki no Kyojin: The Final Season - Kanketsu-henSpecial,2,Mar 2023 - May 2023
11,12,"Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Mar 1997309,193 members",9.02,Ginga Eiyuu DensetsuOVA,110,Jan 1988 - Mar 1997
12,13,"Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (13 eps)Jul 2023 - Aug 2023 178,482 members",8.99,Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV,13,Jul 2023 - Aug 2023
13,14,"Fruits Basket: The FinalTV (13 eps)Apr 2021 - Jun 2021443,882 membersManga StoreVolume 1€6.66Preview",8.99,Fruits Basket: The FinalTV,13,Apr 2021 - Jun 2021
14,15,"Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 members",8.98,Gintama.TV,12,Jan 2017 - Mar 2017
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,418 members",8.94,GintamaTV,201,Apr 2006 - Mar 2010
16,17,"Koe no KatachiMovie (1 eps)Sep 2016 - Sep 20162,228,957 membersManga StoreVolume 1€10.99Preview",8.94,Koe no KatachiMovie,1,Sep 2016 - Sep 2016
17,18,"3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 - Mar 2018388,358 members",8.93,3-gatsu no Lion 2nd SeasonTV,22,Oct 2017 - Mar 2018
18,19,"Clannad: After StoryTV (24 eps)Oct 2008 - Mar 20091,160,879 members",8.93,Clannad: After StoryTV,24,Oct 2008 - Mar 2009
19,20,"Code Geass: Hangyaku no Lelouch R2TV (25 eps)Apr 2008 - Sep 20081,720,715 members",8.91,Code Geass: Hangyaku no Lelouch R2TV,25,Apr 2008 - Sep 2008
20,21,"Gintama Movie 2: Kanketsu-hen - Yorozuya yo Eien NareMovie (1 eps)Jul 2013 - Jul 2013232,388 members",8.91,Gintama Movie 2: Kanketsu-hen - Yorozuya yo Eien NareMovie,1,Jul 2013 - Jul 2013
21,22,"Violet Evergarden MovieMovie (1 eps)Sep 2020 - Sep 2020564,225 members",8.89,Violet Evergarden MovieMovie,1,Sep 2020 - Sep 2020
22,23,"Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 - Aug 2017385,248 members",8.88,Owarimonogatari 2nd SeasonTV,7,Aug 2017 - Aug 2017
23,24,"Gintama.: Shirogane no Tamashii-hen - Kouhan-senTV (14 eps)Jul 2018 - Oct 2018189,172 members",8.88,Gintama.: Shirogane no Tamashii-hen - Kouhan-senTV,14,Jul 2018 - Oct 2018
24,25,"MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081 members",8.87,MonsterTV,74,Apr 2004 - Sep 2005
25,26,"Kimi no Na wa.Movie (1 eps)Aug 2016 - Aug 20162,635,814 membersManga StoreVolume 1€4.58Preview",8.84,Kimi no Na wa.Movie,1,Aug 2016 - Aug 2016
26,27,"Kaguya-sama wa Kokurasetai: First Kiss wa OwaranaiMovie (1 eps)Dec 2022 - Dec 2022205,150 members",8.84,Kaguya-sama wa Kokurasetai: First Kiss wa OwaranaiMovie,1,Dec 2022 - Dec 2022
27,28,"Bocchi the Rock!TV (12 eps)Oct 2022 - Dec 2022464,981 members",8.83,Bocchi the Rock!TV,12,Oct 2022 - Dec 2022
28,29,"The First Slam DunkMovie (1 eps)Dec 2022 - Dec 202227,063 members",8.83,The First Slam DunkMovie,1,Dec 2022 - Dec 2022
29,30,"Vinland Saga Season 2TV (24 eps)Jan 2023 - Jun 2023495,454 membersManga StoreVolume 1€17.99Preview",8.82,Vinland Saga Season 2TV,24,Jan 2023 - Jun 2023
30,31,"Jujutsu Kaisen 2nd SeasonTV (23 eps)Jul 2023 - Aug 2023 556,301 members",8.82,Jujutsu Kaisen 2nd SeasonTV,23,Jul 2023 - Aug 2023
31,32,"Gintama.: Shirogane no Tamashii-henTV (12 eps)Jan 2018 - Mar 2018203,540 members",8.81,Gintama.: Shirogane no Tamashii-henTV,12,Jan 2018 - Mar 2018
32,33,"Kingdom 3rd SeasonTV (26 eps)Apr 2020 - Oct 202193,645 members",8.81,Kingdom 3rd SeasonTV,26,Apr 2020 - Oct 2021
33,34,"Mob Psycho 100 IITV (13 eps)Jan 2019 - Apr 20191,458,089 members",8.80,Mob Psycho 100 IITV,13,Jan 2019 - Apr 2019
34,35,"Shingeki no Kyojin: The Final SeasonTV (16 eps)Dec 2020 - Mar 20211,882,760 membersManga StoreVolume 1€10.99Preview",8.80,Shingeki no Kyojin: The Final SeasonTV,16,Dec 2020 - Mar 2021
35,36,"Kimetsu no Yaiba: Yuukaku-henTV (11 eps)Dec 2021 - Feb 20221,302,152 members",8.79,Kimetsu no Yaiba: Yuukaku-henTV,11,Dec 2021 - Feb 2022
36,37,"Kizumonogatari III: Reiketsu-henMovie (1 eps)Jan 2017 - Jan 2017445,640 membersManga StorePart1€9.99Preview",8.79,Kizumonogatari III: Reiketsu-henMovie,1,Jan 2017 - Jan 2017
37,38,"""Oshi no Ko""TV (11 eps)Apr 2023 - Jun 2023645,856 members",8.79,"""Oshi no Ko""TV",11,Apr 2023 - Jun 2023
38,39,"Haikyuu!! Karasuno Koukou vs. Shiratorizawa Gakuen KoukouTV (10 eps)Oct 2016 - Dec 20161,157,497 members",8.78,Haikyuu!! Karasuno Koukou vs. Shiratorizawa Gakuen KoukouTV,10,Oct 2016 - Dec 2016
39,40,"Sen to Chihiro no KamikakushiMovie (1 eps)Jul 2001 - Jul 20011,784,960 members",8.78,Sen to Chihiro no KamikakushiMovie,1,Jul 2001 - Jul 2001
40,41,"Monogatari Series: Second SeasonTV (26 eps)Jul 2013 - Dec 2013653,257 membersManga StoreVolume 1€9.99Preview",8.77,Monogatari Series: Second SeasonTV,26,Jul 2013 - Dec 2013
41,42,"Shingeki no Kyojin: The Final Season Part 2TV (12 eps)Jan 2022 - Apr 20221,170,165 membersManga StoreVolume 1€10.99Preview",8.77,Shingeki no Kyojin: The Final Season Part 2TV,12,Jan 2022 - Apr 2022
42,43,"Hajime no IppoTV (75 eps)Oct 2000 - Mar 2002558,435 members",8.76,Hajime no IppoTV,75,Oct 2000 - Mar 2002
43,44,"Cowboy BebopTV (26 eps)Apr 1998 - Apr 19991,796,109 members",8.75,Cowboy BebopTV,26,Apr 1998 - Apr 1999
44,45,"Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 202255,833 members",8.75,Kingdom 4th SeasonTV,26,Apr 2022 - Oct 2022
45,46,"Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,403,669 membersManga StoreVolume 1€17.99Preview",8.74,Vinland SagaTV,24,Jul 2019 - Dec 2019
46,47,"Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 2014 - Dec 2014257,622 membersManga StoreVolume 1€10.99Preview",8.73,Mushishi Zoku Shou 2nd SeasonTV,10,Oct 2014 - Dec 2014
47,48,"Shouwa Genroku Rakugo Shinjuu: Sukeroku Futatabi-henTV (12 eps)Jan 2017 - Mar 2017182,450 membersManga StoreVolume 1€12.99Preview",8.72,Shouwa Genroku Rakugo Shinjuu: Sukeroku Futatabi-henTV,12,Jan 2017 - Mar 2017
48,49,"Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 2022600,098 members",8.71,Mob Psycho 100 IIITV,12,Oct 2022 - Dec 2022
49,50,"Rurouni Kenshin: Meiji Kenkaku Romantan - Tsuioku-henOVA (4 eps)Feb 1999 - Sep 1999271,108 members",8.71,Rurouni Kenshin: Meiji Kenkaku Romantan - Tsuioku-henOVA,4,Feb 1999 - Sep 1999

In [44]:
#which anime has the highest score

In [45]:
df[df["Score"] == df["Score"].max()]['Anime_name']

0    Fullmetal Alchemist: BrotherhoodTV
Name: Anime_name, dtype: str

In [46]:
# what is the price of each anime's manga

In [47]:
# making a column for the manga's price of each anime
def Manga_prices(x):
      
      price_str = None
      if "Preview" in x:
            contain = x.split("€")
            price_str = contain[1].removesuffix("Preview")
      return price_str

df["Manga price"] = pd.to_numeric(df["Title"].apply(Manga_prices), errors ="coerce")

In [48]:
df

,Rank,Title,Score,Anime_name,Episodes,Anime_date,Manga price
0,1,"Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr 2009 - Jul 20103,218,472 membersManga StoreVolume 1€4.58Preview",9.10,Fullmetal Alchemist: BrotherhoodTV,64,Apr 2009 - Jul 2010,4.58
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473,707 members",9.07,Steins;GateTV,24,Apr 2011 - Sep 2011,NaN
2,3,"Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 - Dec 2022474,138 members",9.06,Bleach: Sennen Kessen-henTV,13,Oct 2022 - Dec 2022,NaN
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 members",9.06,Gintama°TV,51,Apr 2015 - Mar 2016,NaN
4,5,"Shingeki no Kyojin Season 3 Part 2TV (10 eps)Apr 2019 - Jul 20192,146,679 membersManga StoreVolume 1€10.99Preview",9.05,Shingeki no Kyojin Season 3 Part 2TV,10,Apr 2019 - Jul 2019,10.99
5,6,"Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 members",9.04,Gintama'TV,51,Apr 2011 - Mar 2012,NaN
6,7,"Gintama: The FinalMovie (1 eps)Jan 2021 - Jan 2021137,208 members",9.04,Gintama: The FinalMovie,1,Jan 2021 - Jan 2021,NaN
7,8,"Hunter x Hunter TV (148 eps)Oct 2011 - Sep 20142,701,154 members",9.04,Hunter x Hunter TV,148,Oct 2011 - Sep 2014,NaN
8,9,"Kaguya-sama wa Kokurasetai: Ultra RomanticTV (13 eps)Apr 2022 - Jun 2022851,445 members",9.04,Kaguya-sama wa Kokurasetai: Ultra RomanticTV,13,Apr 2022 - Jun 2022,NaN
9,10,"Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2013313,446 members",9.03,Gintama': EnchousenTV,13,Oct 2012 - Mar 2013,NaN
10,11,"Shingeki no Kyojin: The Final Season - Kanketsu-henSpecial (2 eps)Mar 2023 - May 2023472,340 membersManga StoreVolume 1€10.99Preview",9.03,Shingeki no Kyojin: The Final Season - Kanketsu-henSpecial,2,Mar 2023 - May 2023,10.99
11,12,"Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Mar 1997309,193 members",9.02,Ginga Eiyuu DensetsuOVA,110,Jan 1988 - Mar 1997,NaN
12,13,"Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (13 eps)Jul 2023 - Aug 2023 178,482 members",8.99,Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV,13,Jul 2023 - Aug 2023,NaN
13,14,"Fruits Basket: The FinalTV (13 eps)Apr 2021 - Jun 2021443,882 membersManga StoreVolume 1€6.66Preview",8.99,Fruits Basket: The FinalTV,13,Apr 2021 - Jun 2021,6.66
14,15,"Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 members",8.98,Gintama.TV,12,Jan 2017 - Mar 2017,NaN
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,418 members",8.94,GintamaTV,201,Apr 2006 - Mar 2010,NaN
16,17,"Koe no KatachiMovie (1 eps)Sep 2016 - Sep 20162,228,957 membersManga StoreVolume 1€10.99Preview",8.94,Koe no KatachiMovie,1,Sep 2016 - Sep 2016,10.99
17,18,"3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 - Mar 2018388,358 members",8.93,3-gatsu no Lion 2nd SeasonTV,22,Oct 2017 - Mar 2018,NaN
18,19,"Clannad: After StoryTV (24 eps)Oct 2008 - Mar 20091,160,879 members",8.93,Clannad: After StoryTV,24,Oct 2008 - Mar 2009,NaN
19,20,"Code Geass: Hangyaku no Lelouch R2TV (25 eps)Apr 2008 - Sep 20081,720,715 members",8.91,Code Geass: Hangyaku no Lelouch R2TV,25,Apr 2008 - Sep 2008,NaN
20,21,"Gintama Movie 2: Kanketsu-hen - Yorozuya yo Eien NareMovie (1 eps)Jul 2013 - Jul 2013232,388 members",8.91,Gintama Movie 2: Kanketsu-hen - Yorozuya yo Eien NareMovie,1,Jul 2013 - Jul 2013,NaN
21,22,"Violet Evergarden MovieMovie (1 eps)Sep 2020 - Sep 2020564,225 members",8.89,Violet Evergarden MovieMovie,1,Sep 2020 - Sep 2020,NaN
22,23,"Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 - Aug 2017385,248 members",8.88,Owarimonogatari 2nd SeasonTV,7,Aug 2017 - Aug 2017,NaN
23,24,"Gintama.: Shirogane no Tamashii-hen - Kouhan-senTV (14 eps)Jul 2018 - Oct 2018189,172 members",8.88,Gintama.: Shirogane no Tamashii-hen - Kouhan-senTV,14,Jul 2018 - Oct 2018,NaN
24,25,"MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081 members",8.87,MonsterTV,74,Apr 2004 - Sep 2005,NaN
25,26,"Kimi no Na wa.Movie (1 eps)Aug 2016 - Aug 20162,635,814 membersManga StoreVolume 1€4.58Preview",8.84,Kimi no Na wa.Movie,1,Aug 2016 - Aug 2016,4.58
26,27,"Kaguya-sama wa Kokurasetai: First Kiss wa OwaranaiMovie (1 eps)Dec 2022 - Dec 2022205,150 members",8.84,Kaguya-sama wa Kokurasetai: First Kiss wa OwaranaiMovie,1,Dec 2022 - Dec 2022,NaN
27,28,"Bocchi the Rock!TV (12 eps)Oct 2022 - Dec 2022464,981 members",8.83,Bocchi the Rock!TV,12,Oct 2022 - Dec 2022,NaN
28,29,"The First Slam DunkMovie (1 eps)Dec 2022 - Dec 202227,063 members",8.83,The First Slam DunkMovie,1,Dec 2022 - Dec 2022,NaN
29,30,"Vinland Saga Season 2TV (24 eps)Jan 2023 - Jun 2023495,454 membersManga StoreVolume 1€17.99Preview",8.82,Vinland Saga Season 2TV,24,Jan 2023 - Jun 2023,17.99
30,31,"Jujutsu Kaisen 2nd SeasonTV (23 eps)Jul 2023 - Aug 2023 556,301 members",8.82,Jujutsu Kaisen 2nd SeasonTV,23,Jul 2023 - Aug 2023,NaN
31,32,"Gintama.: Shirogane no Tamashii-henTV (12 eps)Jan 2018 - Mar 2018203,540 members",8.81,Gintama.: Shirogane no Tamashii-henTV,12,Jan 2018 - Mar 2018,NaN
32,33,"Kingdom 3rd SeasonTV (26 eps)Apr 2020 - Oct 202193,645 members",8.81,Kingdom 3rd SeasonTV,26,Apr 2020 - Oct 2021,NaN
33,34,"Mob Psycho 100 IITV (13 eps)Jan 2019 - Apr 20191,458,089 members",8.80,Mob Psycho 100 IITV,13,Jan 2019 - Apr 2019,NaN
34,35,"Shingeki no Kyojin: The Final SeasonTV (16 eps)Dec 2020 - Mar 20211,882,760 membersManga StoreVolume 1€10.99Preview",8.80,Shingeki no Kyojin: The Final SeasonTV,16,Dec 2020 - Mar 2021,10.99
35,36,"Kimetsu no Yaiba: Yuukaku-henTV (11 eps)Dec 2021 - Feb 20221,302,152 members",8.79,Kimetsu no Yaiba: Yuukaku-henTV,11,Dec 2021 - Feb 2022,NaN
36,37,"Kizumonogatari III: Reiketsu-henMovie (1 eps)Jan 2017 - Jan 2017445,640 membersManga StorePart1€9.99Preview",8.79,Kizumonogatari III: Reiketsu-henMovie,1,Jan 2017 - Jan 2017,9.99
37,38,"""Oshi no Ko""TV (11 eps)Apr 2023 - Jun 2023645,856 members",8.79,"""Oshi no Ko""TV",11,Apr 2023 - Jun 2023,NaN
38,39,"Haikyuu!! Karasuno Koukou vs. Shiratorizawa Gakuen KoukouTV (10 eps)Oct 2016 - Dec 20161,157,497 members",8.78,Haikyuu!! Karasuno Koukou vs. Shiratorizawa Gakuen KoukouTV,10,Oct 2016 - Dec 2016,NaN
39,40,"Sen to Chihiro no KamikakushiMovie (1 eps)Jul 2001 - Jul 20011,784,960 members",8.78,Sen to Chihiro no KamikakushiMovie,1,Jul 2001 - Jul 2001,NaN
40,41,"Monogatari Series: Second SeasonTV (26 eps)Jul 2013 - Dec 2013653,257 membersManga StoreVolume 1€9.99Preview",8.77,Monogatari Series: Second SeasonTV,26,Jul 2013 - Dec 2013,9.99
41,42,"Shingeki no Kyojin: The Final Season Part 2TV (12 eps)Jan 2022 - Apr 20221,170,165 membersManga StoreVolume 1€10.99Preview",8.77,Shingeki no Kyojin: The Final Season Part 2TV,12,Jan 2022 - Apr 2022,10.99
42,43,"Hajime no IppoTV (75 eps)Oct 2000 - Mar 2002558,435 members",8.76,Hajime no IppoTV,75,Oct 2000 - Mar 2002,NaN
43,44,"Cowboy BebopTV (26 eps)Apr 1998 - Apr 19991,796,109 members",8.75,Cowboy BebopTV,26,Apr 1998 - Apr 1999,NaN
44,45,"Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 202255,833 members",8.75,Kingdom 4th SeasonTV,26,Apr 2022 - Oct 2022,NaN
45,46,"Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,403,669 membersManga StoreVolume 1€17.99Preview",8.74,Vinland SagaTV,24,Jul 2019 - Dec 2019,17.99
46,47,"Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 2014 - Dec 2014257,622 membersManga StoreVolume 1€10.99Preview",8.73,Mushishi Zoku Shou 2nd SeasonTV,10,Oct 2014 - Dec 2014,10.99
47,48,"Shouwa Genroku Rakugo Shinjuu: Sukeroku Futatabi-henTV (12 eps)Jan 2017 - Mar 2017182,450 membersManga StoreVolume 1€12.99Preview",8.72,Shouwa Genroku Rakugo Shinjuu: Sukeroku Futatabi-henTV,12,Jan 2017 - Mar 2017,12.99
48,49,"Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 2022600,098 members",8.71,Mob Psycho 100 IIITV,12,Oct 2022 - Dec 2022,NaN
49,50,"Rurouni Kenshin: Meiji Kenkaku Romantan - Tsuioku-henOVA (4 eps)Feb 1999 - Sep 1999271,108 members",8.71,Rurouni Kenshin: Meiji Kenkaku Romantan - Tsuioku-henOVA,4,Feb 1999 - Sep 1999,NaN

In [49]:
df.loc[0]

Rank                                                                                                                        1
Title          Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr 2009 - Jul 20103,218,472 membersManga StoreVolume 1€4.58Preview
Score                                                                                                                     9.1
Anime_name                                                                                Fullmetal Alchemist: BrotherhoodTV
Episodes                                                                                                                   64
Anime_date                                                                                                Apr 2009 - Jul 2010
Manga price                                                                                                              4.58
Name: 0, dtype: object

In [50]:
#which anime has the highest episode count

In [51]:
df.sort_values('Episodes', ascending=False).iloc[0]

Rank                                                                16
Title          GintamaTV (201 eps)Apr 2006 - Mar 20101,034,418 members
Score                                                             8.94
Anime_name                                                  GintamaTV
Episodes                                                           201
Anime_date                                         Apr 2006 - Mar 2010
Manga price                                                        NaN
Name: 15, dtype: object

In [52]:
#give me top 5 highest scoring anime

In [53]:
df.sort_values(by= 'Score',ascending=False).head()['Anime_name']

0      Fullmetal Alchemist: BrotherhoodTV
1                           Steins;GateTV
2             Bleach: Sennen Kessen-henTV
3                              Gintama°TV
4    Shingeki no Kyojin Season 3 Part 2TV
Name: Anime_name, dtype: str

In [54]:
#animes with top 5 episode count

In [55]:
df.sort_values('Episodes', ascending=False).head()

,Rank,Title,Score,Anime_name,Episodes,Anime_date,Manga price
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,418 members",8.94,GintamaTV,201,Apr 2006 - Mar 2010,NaN
7,8,"Hunter x Hunter TV (148 eps)Oct 2011 - Sep 20142,701,154 members",9.04,Hunter x Hunter TV,148,Oct 2011 - Sep 2014,NaN
11,12,"Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Mar 1997309,193 members",9.02,Ginga Eiyuu DensetsuOVA,110,Jan 1988 - Mar 1997,NaN
42,43,"Hajime no IppoTV (75 eps)Oct 2000 - Mar 2002558,435 members",8.76,Hajime no IppoTV,75,Oct 2000 - Mar 2002,NaN
24,25,"MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081 members",8.87,MonsterTV,74,Apr 2004 - Sep 2005,NaN

In [56]:
#which is the longest running anime

In [57]:
split_time = df["Anime_date"].str.split('-', expand=True)
start_time = split_time[0].str.strip()
end_time = split_time[1].str.strip()

start_month = pd.to_datetime(start_time, format='%b %Y', errors='coerce')
end_month =  pd.to_datetime(end_time, format='%b %Y', errors='coerce')

df["month"] = (end_month.dt.month - start_month.dt.month) + (12*(end_month.dt.year-start_month.dt.year))

In [58]:
df.loc[df['month'] == df["month"].max(),"Anime_name"]

11    Ginga Eiyuu DensetsuOVA
Name: Anime_name, dtype: str

In [59]:
df['month']

0      15
1       5
2       2
3      11
4       3
5      11
6       0
7      35
8       2
9       5
10      2
11    110
12      1
13      2
14      2
15     47
16      0
17      5
18      5
19      5
20      0
21      0
22      0
23      3
24     17
25      0
26      0
27      2
28      0
29      5
30      1
31      2
32     18
33      3
34      3
35      2
36      0
37      2
38      2
39      0
40      5
41      3
42     17
43     12
44      6
45      5
46      2
47      2
48      2
49      7
Name: month, dtype: int32

In [60]:
df

,Rank,Title,Score,Anime_name,Episodes,Anime_date,Manga price,month
0,1,"Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr 2009 - Jul 20103,218,472 membersManga StoreVolume 1€4.58Preview",9.10,Fullmetal Alchemist: BrotherhoodTV,64,Apr 2009 - Jul 2010,4.58,15
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473,707 members",9.07,Steins;GateTV,24,Apr 2011 - Sep 2011,NaN,5
2,3,"Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 - Dec 2022474,138 members",9.06,Bleach: Sennen Kessen-henTV,13,Oct 2022 - Dec 2022,NaN,2
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 members",9.06,Gintama°TV,51,Apr 2015 - Mar 2016,NaN,11
4,5,"Shingeki no Kyojin Season 3 Part 2TV (10 eps)Apr 2019 - Jul 20192,146,679 membersManga StoreVolume 1€10.99Preview",9.05,Shingeki no Kyojin Season 3 Part 2TV,10,Apr 2019 - Jul 2019,10.99,3
5,6,"Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 members",9.04,Gintama'TV,51,Apr 2011 - Mar 2012,NaN,11
6,7,"Gintama: The FinalMovie (1 eps)Jan 2021 - Jan 2021137,208 members",9.04,Gintama: The FinalMovie,1,Jan 2021 - Jan 2021,NaN,0
7,8,"Hunter x Hunter TV (148 eps)Oct 2011 - Sep 20142,701,154 members",9.04,Hunter x Hunter TV,148,Oct 2011 - Sep 2014,NaN,35
8,9,"Kaguya-sama wa Kokurasetai: Ultra RomanticTV (13 eps)Apr 2022 - Jun 2022851,445 members",9.04,Kaguya-sama wa Kokurasetai: Ultra RomanticTV,13,Apr 2022 - Jun 2022,NaN,2
9,10,"Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2013313,446 members",9.03,Gintama': EnchousenTV,13,Oct 2012 - Mar 2013,NaN,5
10,11,"Shingeki no Kyojin: The Final Season - Kanketsu-henSpecial (2 eps)Mar 2023 - May 2023472,340 membersManga StoreVolume 1€10.99Preview",9.03,Shingeki no Kyojin: The Final Season - Kanketsu-henSpecial,2,Mar 2023 - May 2023,10.99,2
11,12,"Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Mar 1997309,193 members",9.02,Ginga Eiyuu DensetsuOVA,110,Jan 1988 - Mar 1997,NaN,110
12,13,"Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (13 eps)Jul 2023 - Aug 2023 178,482 members",8.99,Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV,13,Jul 2023 - Aug 2023,NaN,1
13,14,"Fruits Basket: The FinalTV (13 eps)Apr 2021 - Jun 2021443,882 membersManga StoreVolume 1€6.66Preview",8.99,Fruits Basket: The FinalTV,13,Apr 2021 - Jun 2021,6.66,2
14,15,"Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 members",8.98,Gintama.TV,12,Jan 2017 - Mar 2017,NaN,2
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,418 members",8.94,GintamaTV,201,Apr 2006 - Mar 2010,NaN,47
16,17,"Koe no KatachiMovie (1 eps)Sep 2016 - Sep 20162,228,957 membersManga StoreVolume 1€10.99Preview",8.94,Koe no KatachiMovie,1,Sep 2016 - Sep 2016,10.99,0
17,18,"3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 - Mar 2018388,358 members",8.93,3-gatsu no Lion 2nd SeasonTV,22,Oct 2017 - Mar 2018,NaN,5
18,19,"Clannad: After StoryTV (24 eps)Oct 2008 - Mar 20091,160,879 members",8.93,Clannad: After StoryTV,24,Oct 2008 - Mar 2009,NaN,5
19,20,"Code Geass: Hangyaku no Lelouch R2TV (25 eps)Apr 2008 - Sep 20081,720,715 members",8.91,Code Geass: Hangyaku no Lelouch R2TV,25,Apr 2008 - Sep 2008,NaN,5
20,21,"Gintama Movie 2: Kanketsu-hen - Yorozuya yo Eien NareMovie (1 eps)Jul 2013 - Jul 2013232,388 members",8.91,Gintama Movie 2: Kanketsu-hen - Yorozuya yo Eien NareMovie,1,Jul 2013 - Jul 2013,NaN,0
21,22,"Violet Evergarden MovieMovie (1 eps)Sep 2020 - Sep 2020564,225 members",8.89,Violet Evergarden MovieMovie,1,Sep 2020 - Sep 2020,NaN,0
22,23,"Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 - Aug 2017385,248 members",8.88,Owarimonogatari 2nd SeasonTV,7,Aug 2017 - Aug 2017,NaN,0
23,24,"Gintama.: Shirogane no Tamashii-hen - Kouhan-senTV (14 eps)Jul 2018 - Oct 2018189,172 members",8.88,Gintama.: Shirogane no Tamashii-hen - Kouhan-senTV,14,Jul 2018 - Oct 2018,NaN,3
24,25,"MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081 members",8.87,MonsterTV,74,Apr 2004 - Sep 2005,NaN,17
25,26,"Kimi no Na wa.Movie (1 eps)Aug 2016 - Aug 20162,635,814 membersManga StoreVolume 1€4.58Preview",8.84,Kimi no Na wa.Movie,1,Aug 2016 - Aug 2016,4.58,0
26,27,"Kaguya-sama wa Kokurasetai: First Kiss wa OwaranaiMovie (1 eps)Dec 2022 - Dec 2022205,150 members",8.84,Kaguya-sama wa Kokurasetai: First Kiss wa OwaranaiMovie,1,Dec 2022 - Dec 2022,NaN,0
27,28,"Bocchi the Rock!TV (12 eps)Oct 2022 - Dec 2022464,981 members",8.83,Bocchi the Rock!TV,12,Oct 2022 - Dec 2022,NaN,2
28,29,"The First Slam DunkMovie (1 eps)Dec 2022 - Dec 202227,063 members",8.83,The First Slam DunkMovie,1,Dec 2022 - Dec 2022,NaN,0
29,30,"Vinland Saga Season 2TV (24 eps)Jan 2023 - Jun 2023495,454 membersManga StoreVolume 1€17.99Preview",8.82,Vinland Saga Season 2TV,24,Jan 2023 - Jun 2023,17.99,5
30,31,"Jujutsu Kaisen 2nd SeasonTV (23 eps)Jul 2023 - Aug 2023 556,301 members",8.82,Jujutsu Kaisen 2nd SeasonTV,23,Jul 2023 - Aug 2023,NaN,1
31,32,"Gintama.: Shirogane no Tamashii-henTV (12 eps)Jan 2018 - Mar 2018203,540 members",8.81,Gintama.: Shirogane no Tamashii-henTV,12,Jan 2018 - Mar 2018,NaN,2
32,33,"Kingdom 3rd SeasonTV (26 eps)Apr 2020 - Oct 202193,645 members",8.81,Kingdom 3rd SeasonTV,26,Apr 2020 - Oct 2021,NaN,18
33,34,"Mob Psycho 100 IITV (13 eps)Jan 2019 - Apr 20191,458,089 members",8.80,Mob Psycho 100 IITV,13,Jan 2019 - Apr 2019,NaN,3
34,35,"Shingeki no Kyojin: The Final SeasonTV (16 eps)Dec 2020 - Mar 20211,882,760 membersManga StoreVolume 1€10.99Preview",8.80,Shingeki no Kyojin: The Final SeasonTV,16,Dec 2020 - Mar 2021,10.99,3
35,36,"Kimetsu no Yaiba: Yuukaku-henTV (11 eps)Dec 2021 - Feb 20221,302,152 members",8.79,Kimetsu no Yaiba: Yuukaku-henTV,11,Dec 2021 - Feb 2022,NaN,2
36,37,"Kizumonogatari III: Reiketsu-henMovie (1 eps)Jan 2017 - Jan 2017445,640 membersManga StorePart1€9.99Preview",8.79,Kizumonogatari III: Reiketsu-henMovie,1,Jan 2017 - Jan 2017,9.99,0
37,38,"""Oshi no Ko""TV (11 eps)Apr 2023 - Jun 2023645,856 members",8.79,"""Oshi no Ko""TV",11,Apr 2023 - Jun 2023,NaN,2
38,39,"Haikyuu!! Karasuno Koukou vs. Shiratorizawa Gakuen KoukouTV (10 eps)Oct 2016 - Dec 20161,157,497 members",8.78,Haikyuu!! Karasuno Koukou vs. Shiratorizawa Gakuen KoukouTV,10,Oct 2016 - Dec 2016,NaN,2
39,40,"Sen to Chihiro no KamikakushiMovie (1 eps)Jul 2001 - Jul 20011,784,960 members",8.78,Sen to Chihiro no KamikakushiMovie,1,Jul 2001 - Jul 2001,NaN,0
40,41,"Monogatari Series: Second SeasonTV (26 eps)Jul 2013 - Dec 2013653,257 membersManga StoreVolume 1€9.99Preview",8.77,Monogatari Series: Second SeasonTV,26,Jul 2013 - Dec 2013,9.99,5
41,42,"Shingeki no Kyojin: The Final Season Part 2TV (12 eps)Jan 2022 - Apr 20221,170,165 membersManga StoreVolume 1€10.99Preview",8.77,Shingeki no Kyojin: The Final Season Part 2TV,12,Jan 2022 - Apr 2022,10.99,3
42,43,"Hajime no IppoTV (75 eps)Oct 2000 - Mar 2002558,435 members",8.76,Hajime no IppoTV,75,Oct 2000 - Mar 2002,NaN,17
43,44,"Cowboy BebopTV (26 eps)Apr 1998 - Apr 19991,796,109 members",8.75,Cowboy BebopTV,26,Apr 1998 - Apr 1999,NaN,12
44,45,"Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 202255,833 members",8.75,Kingdom 4th SeasonTV,26,Apr 2022 - Oct 2022,NaN,6
45,46,"Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,403,669 membersManga StoreVolume 1€17.99Preview",8.74,Vinland SagaTV,24,Jul 2019 - Dec 2019,17.99,5
46,47,"Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 2014 - Dec 2014257,622 membersManga StoreVolume 1€10.99Preview",8.73,Mushishi Zoku Shou 2nd SeasonTV,10,Oct 2014 - Dec 2014,10.99,2
47,48,"Shouwa Genroku Rakugo Shinjuu: Sukeroku Futatabi-henTV (12 eps)Jan 2017 - Mar 2017182,450 membersManga StoreVolume 1€12.99Preview",8.72,Shouwa Genroku Rakugo Shinjuu: Sukeroku Futatabi-henTV,12,Jan 2017 - Mar 2017,12.99,2
48,49,"Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 2022600,098 members",8.71,Mob Psycho 100 IIITV,12,Oct 2022 - Dec 2022,NaN,2
49,50,"Rurouni Kenshin: Meiji Kenkaku Romantan - Tsuioku-henOVA (4 eps)Feb 1999 - Sep 1999271,108 members",8.71,Rurouni Kenshin: Meiji Kenkaku Romantan - Tsuioku-henOVA,4,Feb 1999 - Sep 1999,NaN,7

In [61]:
#make a column for member count

In [62]:
def Members_number(x):

    split_1 = x.rsplit(' - ', maxsplit = 1)
    temp_str = split_1[1]

    if "membersManga" in x:
        temp_str1 = temp_str.split(' membersManga ')
        temp_str2 = temp_str1[0]

    else:
        temp_str1 = temp_str.split(' members ')
        temp_str2 = temp_str1[0]

    final_str = temp_str2[8:].removesuffix(' members')
    last_str = final_str.replace(',','')
    return last_str

df["Member_count"] = df["Title"].apply(Members_number).astype(int)

In [63]:
#show the top 5 anime with highest Member Counts

In [64]:
df.sort_values(by='Member_count', ascending = False)
df.head()

,Rank,Title,Score,Anime_name,Episodes,Anime_date,Manga price,month,Member_count
0,1,"Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr 2009 - Jul 20103,218,472 membersManga StoreVolume 1€4.58Preview",9.10,Fullmetal Alchemist: BrotherhoodTV,64,Apr 2009 - Jul 2010,4.58,15,3218472
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473,707 members",9.07,Steins;GateTV,24,Apr 2011 - Sep 2011,NaN,5,2473707
2,3,"Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 - Dec 2022474,138 members",9.06,Bleach: Sennen Kessen-henTV,13,Oct 2022 - Dec 2022,NaN,2,474138
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 members",9.06,Gintama°TV,51,Apr 2015 - Mar 2016,NaN,11,605113
4,5,"Shingeki no Kyojin Season 3 Part 2TV (10 eps)Apr 2019 - Jul 20192,146,679 membersManga StoreVolume 1€10.99Preview",9.05,Shingeki no Kyojin Season 3 Part 2TV,10,Apr 2019 - Jul 2019,10.99,3,2146679

In [65]:
#remove the Title and Rank column from the data

In [66]:
df = df.drop(['Title','Rank'], axis=1)

In [67]:
#reorder the dataframe

In [68]:
new_order = ['Anime_name', 'Episodes','Score','Manga price', 'Anime_date','month','Member_count']
df = df[new_order]

In [69]:
df

,Anime_name,Episodes,Score,Manga price,Anime_date,month,Member_count
0,Fullmetal Alchemist: BrotherhoodTV,64,9.10,4.58,Apr 2009 - Jul 2010,15,3218472
1,Steins;GateTV,24,9.07,NaN,Apr 2011 - Sep 2011,5,2473707
2,Bleach: Sennen Kessen-henTV,13,9.06,NaN,Oct 2022 - Dec 2022,2,474138
3,Gintama°TV,51,9.06,NaN,Apr 2015 - Mar 2016,11,605113
4,Shingeki no Kyojin Season 3 Part 2TV,10,9.05,10.99,Apr 2019 - Jul 2019,3,2146679
5,Gintama'TV,51,9.04,NaN,Apr 2011 - Mar 2012,11,534105
6,Gintama: The FinalMovie,1,9.04,NaN,Jan 2021 - Jan 2021,0,137208
7,Hunter x Hunter TV,148,9.04,NaN,Oct 2011 - Sep 2014,35,2701154
8,Kaguya-sama wa Kokurasetai: Ultra RomanticTV,13,9.04,NaN,Apr 2022 - Jun 2022,2,851445
9,Gintama': EnchousenTV,13,9.03,NaN,Oct 2012 - Mar 2013,5,313446
10,Shingeki no Kyojin: The Final Season - Kanketsu-henSpecial,2,9.03,10.99,Mar 2023 - May 2023,2,472340
11,Ginga Eiyuu DensetsuOVA,110,9.02,NaN,Jan 1988 - Mar 1997,110,309193
12,Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV,13,8.99,NaN,Jul 2023 - Aug 2023,1,178482
13,Fruits Basket: The FinalTV,13,8.99,6.66,Apr 2021 - Jun 2021,2,443882
14,Gintama.TV,12,8.98,NaN,Jan 2017 - Mar 2017,2,302232
15,GintamaTV,201,8.94,NaN,Apr 2006 - Mar 2010,47,1034418
16,Koe no KatachiMovie,1,8.94,10.99,Sep 2016 - Sep 2016,0,2228957
17,3-gatsu no Lion 2nd SeasonTV,22,8.93,NaN,Oct 2017 - Mar 2018,5,388358
18,Clannad: After StoryTV,24,8.93,NaN,Oct 2008 - Mar 2009,5,1160879
19,Code Geass: Hangyaku no Lelouch R2TV,25,8.91,NaN,Apr 2008 - Sep 2008,5,1720715
20,Gintama Movie 2: Kanketsu-hen - Yorozuya yo Eien NareMovie,1,8.91,NaN,Jul 2013 - Jul 2013,0,232388
21,Violet Evergarden MovieMovie,1,8.89,NaN,Sep 2020 - Sep 2020,0,564225
22,Owarimonogatari 2nd SeasonTV,7,8.88,NaN,Aug 2017 - Aug 2017,0,385248
23,Gintama.: Shirogane no Tamashii-hen - Kouhan-senTV,14,8.88,NaN,Jul 2018 - Oct 2018,3,189172
24,MonsterTV,74,8.87,NaN,Apr 2004 - Sep 2005,17,1041081
25,Kimi no Na wa.Movie,1,8.84,4.58,Aug 2016 - Aug 2016,0,2635814
26,Kaguya-sama wa Kokurasetai: First Kiss wa OwaranaiMovie,1,8.84,NaN,Dec 2022 - Dec 2022,0,205150
27,Bocchi the Rock!TV,12,8.83,NaN,Oct 2022 - Dec 2022,2,464981
28,The First Slam DunkMovie,1,8.83,NaN,Dec 2022 - Dec 2022,0,27063
29,Vinland Saga Season 2TV,24,8.82,17.99,Jan 2023 - Jun 2023,5,495454
30,Jujutsu Kaisen 2nd SeasonTV,23,8.82,NaN,Jul 2023 - Aug 2023,1,556301
31,Gintama.: Shirogane no Tamashii-henTV,12,8.81,NaN,Jan 2018 - Mar 2018,2,203540
32,Kingdom 3rd SeasonTV,26,8.81,NaN,Apr 2020 - Oct 2021,18,93645
33,Mob Psycho 100 IITV,13,8.80,NaN,Jan 2019 - Apr 2019,3,1458089
34,Shingeki no Kyojin: The Final SeasonTV,16,8.80,10.99,Dec 2020 - Mar 2021,3,1882760
35,Kimetsu no Yaiba: Yuukaku-henTV,11,8.79,NaN,Dec 2021 - Feb 2022,2,1302152
36,Kizumonogatari III: Reiketsu-henMovie,1,8.79,9.99,Jan 2017 - Jan 2017,0,445640
37,"""Oshi no Ko""TV",11,8.79,NaN,Apr 2023 - Jun 2023,2,645856
38,Haikyuu!! Karasuno Koukou vs. Shiratorizawa Gakuen KoukouTV,10,8.78,NaN,Oct 2016 - Dec 2016,2,1157497
39,Sen to Chihiro no KamikakushiMovie,1,8.78,NaN,Jul 2001 - Jul 2001,0,1784960
40,Monogatari Series: Second SeasonTV,26,8.77,9.99,Jul 2013 - Dec 2013,5,653257
41,Shingeki no Kyojin: The Final Season Part 2TV,12,8.77,10.99,Jan 2022 - Apr 2022,3,1170165
42,Hajime no IppoTV,75,8.76,NaN,Oct 2000 - Mar 2002,17,558435
43,Cowboy BebopTV,26,8.75,NaN,Apr 1998 - Apr 1999,12,1796109
44,Kingdom 4th SeasonTV,26,8.75,NaN,Apr 2022 - Oct 2022,6,55833
45,Vinland SagaTV,24,8.74,17.99,Jul 2019 - Dec 2019,5,1403669
46,Mushishi Zoku Shou 2nd SeasonTV,10,8.73,10.99,Oct 2014 - Dec 2014,2,257622
47,Shouwa Genroku Rakugo Shinjuu: Sukeroku Futatabi-henTV,12,8.72,12.99,Jan 2017 - Mar 2017,2,182450
48,Mob Psycho 100 IIITV,12,8.71,NaN,Oct 2022 - Dec 2022,2,600098
49,Rurouni Kenshin: Meiji Kenkaku Romantan - Tsuioku-henOVA,4,8.71,NaN,Feb 1999 - Sep 1999,7,271108